#!/usr/bin/python2.7

import sys
import signal

signal.signal(signal.SIGINT, signal.SIG_IGN)

clip_file = "/tmp/clip.tmp"
if (sys.stdin.isatty()):
	try:
		with open(clip_file, "r") as f:
			sys.stdout.write(f.read())
	except Exception as error:
		sys.stderr.write("clipboard is not set\n")
if (sys.stdout.isatty()):
	try:
		with open(clip_file, "w") as f:
			try:
				f.write(sys.stdin.read())
			except:
					pass
	except Exception as error:
		sys.stderr.write("can't open {}\n".format(clip_file))

sys.stderr.flush()
